---
field_formatter_info:
  amount_formatted:
    label: Formatted
    field types: [ amount ]
    settings:
      scale: 2
      unitsdisplay: symbolafter
  amount_unformatted:
    label: Unformatted
    field types: [ amount ]
    settings:
      minscale: 2
  amount_raw:
    label: Raw
    field types: [ amount ]
    settings:
      minscale: 7

field_widget_info:
  [ field, amount, widget info ]

field_info:
  amount:
    _fetch: [ field, amount, field info ]

}


...